### ISSUE TITLE
Program trying to bind to virtual machine's network card?

### ISSUE THREAD

**Issue by mkbwong** [jgoldshlag/padherder_proxy#1]
I'm having some trouble getting this program to route any traffic at all. I think it's because it's trying to bind to my virtual machine's NIC instead of my actual physical NIC. The program is telling me to use a proxy/DNS IP from one of my VMs which is 169.254.x.x, but I think the expected behavior should be to use my LAN IP of 192.168.1.x? Please let me know if you need more information/clarification.

**Comment by jgoldshlag** [comment]
I'll add an option to override the interface it is binding to. Are you running from source? I don't have a machine here with multiple IPs to test with

**Comment by mkbwong** [comment]
I'm running from the precompiled releases.

Edit: I tried running from source on my Linux machine, which has a pretty standard setup without weird extra NICs. It's trying to bind to localhost there instead. I think since you're using `socket.gethostbyname(socket.gethostname())` to get the IP, it finds this by looking up the hostname in the machine's hosts file, which is commonly set to 127.0.0.1 on Linux. You might need a different way of retrieving the LAN IP, or an option to manually enter an IP/override like you said.

For now, I hardcoded my LAN IP and traffic seems to be passing through. I'll check if the padherder functionality works (HK client/Android device)

**Comment by jgoldshlag** [comment]
Try out the latest release, I added an option in settings to choose the IP (in 8066e932872dc7d47e1f2d77eb9271ba4ec96039)

**Comment by mkbwong** [comment]
Thank you, I can confirm that it works great on HK+Android.

**Comment by jgoldshlag** [comment]
awesome, thanks for trying it!
