### ISSUE TITLE
Sometimes reporting incorrect monster type when removing

### ISSUE THREAD

**Issue by TheKat** [jgoldshlag/padherder_proxy#15]
It seems to be cosmetic, but sometimes PADHerder Proxy gets confused and reports on the "wrong" monster types being removed.

I had fused a number of different monsters together (none being Present Egg), then ran through Proxy and this is what was reported. I do not know if "present egg" being the last monster I got in a dungeon is related.

Downloaded current padherder box
Updated monster Mid Water Ninja: current_xp
Updated monster Battle Flower Spirit, Mandrake: current_xp
Updated monster Green DeviNyan: current_xp
Updated monster Winron: current_xp
Removed monster Present Egg
Removed monster Present Egg
Removed monster Present Egg
Removed monster Present Egg
Removed monster Present Egg
Done

**Comment by jgoldshlag** [comment]
Yeah, I noticed that before, and looking at the code, it is showing the wrong name. I'll fix that, along with a couple other little bugs and cut a new release shortly. Thanks for mentioning it

**Comment by jgoldshlag** [comment]
Fixed in 1.10
