### ISSUE TITLE
got error when syncing for the first time

### ISSUE THREAD

**Issue by angelflames1337** [jgoldshlag/padherder_proxy#17]
error as below, am using iOS 9.3

**Comment by angelflames1337** [comment]
I copied everything from the status windows:

You need to set your padherder username in Settings
You need to set your padherder password in Settings
proxy started
Got DNS Request
Got HTTPS request, forwarding
Got HTTPS request, forwarding
Got box data, processing...
Got HTTPS request, forwarding
Got HTTPS request, forwarding
Got HTTPS request, forwarding
Downloaded full monster data
Downloaded current padherder box
Error doing sync:
Traceback (most recent call last):
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 230, in do_sync
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 24, in xp_at_level
TypeError: object of type 'NoneType' has no len()

Please report this error on github

**Comment by jgoldshlag** [comment]
Hmm, sounds like there is a new XP curve on one of your monsters. Are you playing the JP version?

**Comment by angelflames1337** [comment]
Yes i played JP. It isnt compatible isnt it?

**Comment by jgoldshlag** [comment]
Mostly, but there is probably something new in your box that has a different XP curve. I will try to figure out what changed and cut a new version. Note that it will mess up some of the batman monsters when you use it for a JP account because GungHo was dumb and assigned them the same numbers as some other stuff in the US.

**Comment by jgoldshlag** [comment]
Yeah, sure enough, the reincarnation evos of the mystic knights are on an 8,000,000 xp curve. I have a fix in hand, will do a new release tonight

**Comment by angelflames1337** [comment]
Nice, couldnt wait for it! And I never care about batman, only have one monster from the collab so far :p

**Comment by jgoldshlag** [comment]
Fixed in 1.10
