### ISSUE TITLE
error when importing for JP version (seraph?)

### ISSUE THREAD

**Issue by angelflames1337** [jgoldshlag/padherder_proxy#18]
error as below, im gonna go ahead and guess its because of seraph? he is the only new unit I have since last time:

proxy started
Got DNS Request
Got HTTPS request, forwarding
Got HTTPS request, forwarding
Got box data, processing...
Got HTTPS request, forwarding
Got mail data, processing...
Got HTTPS request, forwarding
Downloaded full monster data
Downloaded current padherder box
Error doing sync:
Traceback (most recent call last):
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 230, in do_sync
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 24, in xp_at_level
TypeError: object of type 'NoneType' has no len()

Please report this error on github
Got DNS Request
Got HTTPS request, forwarding
Got mail data, processing...

**Comment by jgoldshlag** [comment]
Yup, and I just fixed this in the new release. Thanks for reporting this!

**Comment by angelflames1337** [comment]
appreciate the quick update, thanks!
