### ISSUE TITLE
Material Count Kept at 0 when Importing JSON File

### ISSUE THREAD

**Issue by Gnod5** [jgoldshlag/padherder_proxy#23]
Not sure if it's a problem with the padproxy I use or padherder but when I upload my box some of the mats don't update. For example, I see this when uploading the JSON file to padherder: "Updated material count for #2722. Awoken Hephaestus to '0'". My padherder proxy, on the other hand, had shown: "Updated material Awoken Hephaestus from 0 to 1" when connecting to my iPhone.

**Comment by Raijinili** [comment]
Might it just be that Padherder's upload code treats Awoken Hephaestus as a non-material monster? Padherder currently separates materials and non-materials.

**Comment by jgoldshlag** [comment]
This is a bug in padherder, file a bug report at https://github.com/madcowfred/padherder-issues/issues for it
