### ISSUE TITLE
error doing sync

### ISSUE THREAD

**Issue by Twyst** [jgoldshlag/padherder_proxy#25]
proxy started
Got DNS Request
Got HTTPS request, forwarding
Got DNS Request
Got HTTPS request, forwarding
Got box data, processing...
Got HTTPS request, forwarding
Downloaded full monster data
Downloaded current padherder box
Updated monster Heavenly Herald, Archangel (id 223935): current_xp, plus_hp, plus_atk
Updated monster Awoken Amaterasu Ohkami (id 223979): current_skill, plus_hp, plus_atk, current_awakening, current_xp
Updated monster Gigas the Great (id 7152518): current_xp, plus_hp
Updated monster Pitch Black Night Princess, Lilith (id 223936): current_xp, current_skill
Error doing sync:
Traceback (most recent call last):
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 183, in do_sync
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 35, in xp_at_level
TypeError: object of type 'NoneType' has no len()

Please report this error on github
NA version - maybe this is due to June Bride event

**Comment by jgoldshlag** [comment]
I am Josh, that is why you see that. They added some new xp curve, I'll cut a new release shortly

**Comment by jgoldshlag** [comment]
Is this using the most recent version? I don't see a monster with an unknown xp curve, and those line numbers look like you might be running an old release.

**Comment by Twyst** [comment]
Could be! I will try asap! I figured and edited after looking at other logs
that your Dropbox ref was supposed to be there :D

**Comment by Twyst** [comment]
Ah yep! I had 2 versions on my PC, used the old one. All good now, thanks so much, keep up the awesome work!
