### ISSUE TITLE
no len()

### ISSUE THREAD

**Issue by k4kirin** [jgoldshlag/padherder_proxy#26]
Hi; I have received an error, which here is the whole log:
"
proxy started
Got DNS Request
Got HTTPS request, forwarding
Got HTTPS request, forwarding
Got box data, processing...
Downloaded full monster data
Got HTTPS request, forwarding
Downloaded current padherder box
Error doing sync:
Traceback (most recent call last):
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 223, in do_sync
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 23, in xp_at_level
TypeError: object of type 'NoneType' has no len()

"
Thank you in advance.

**Comment by GL1TCH3D** [comment]
Did you happen to roll one of the new monsters gremory or ronove?

**Comment by k4kirin** [comment]
No I haven't.
I believe this problem was even before those were released.

**Comment by jgoldshlag** [comment]
This is a missing XP curve bug, and the latest release should fix this.
