### ISSUE TITLE
Starting Proxy Server Error

### ISSUE THREAD

**Issue by mizzpenny** [jgoldshlag/padherder_proxy#27]
I'm on Android (yes I know you're an iOS guy). I configured everything with the Android screenshot and I installed the CA.

So when I set it up and open PAD, I get an error 101. 

Looking at Padheader Proxy, I see the following:

> Got DNS Request
> Error starting HTTPS proxy: Error starting proxy server: error(10013, 'An attempt was made to access a socket in a way forbidden by its access permissions')

I did launch chrome and I do have internet access. I see everysite I am visiting on my phone in the DNS proxy log. 

I have turned off windows firewall and that didn't work. uninstall the CA and reinstall it as wifi (first attempt was as "VPN and APP"

So I'm unsure what am I doing wrong.

**Comment by jgoldshlag** [comment]
This error means you had something on your computer that was running on port 443. Not sure if you fixed this or just gave up, but if you want help trying to figure out what it is, you can use the netstat command on the command line to see what is running on that port.

**Comment by mizzpenny** [comment]
Thanks. I'll revisit this at some point.. Currently got it to work with the modified padlistener on my nexus tablet. its a pain to move my PAD from my phone to my tablet just to sync.. but it works at the moment
