### ISSUE TITLE
Fatal error! Error loading Python DLL

### ISSUE THREAD

**Issue by jonnybonbons** [jgoldshlag/padherder_proxy#29]
![image](https://cloud.githubusercontent.com/assets/14022414/18462995/9da630d0-793b-11e6-86b0-6f070cb69f5f.png)

**Comment by johns996** [comment]
I got the same error when trying to run the .exe file.  I'm using Windows 7.  I tried running the file as a standard user and administrator.  Error code 14001 is "side-by-side configuration is incorrect".  No idea what that means but this page talks about how to trace it: https://github.com/pyinstaller/pyinstaller/issues/1291

**Comment by Madnapali** [comment]
Also having this problem. Started when I went to the newest version. Apparently the pyinstaller package is only necessary if running from source, which I'm not, so I have no idea what is causing this. I'll just go back to the last revision.

Edit: scratch that. Still broken.

**Comment by RogerIrrelevantUK** [comment]
I've had the same issue with some friends I've helped set up.  The problem appears to be the version of the Microsoft Visual C++ redistributable which 2.5 is built on.  The trace shows a dependency on version 9.0.30729.6161 but this appears to be part of a security update only, so it's very hit & miss whether it will work on any particular PC.

The quickest option might be putting a link to the version of the C++ redistributable currently in use on the compilation computer.  That way we can at least install that!

**Comment by NiteCyper** [comment]
Me too.

**Comment by zedekblue** [comment]
Been having this issue as well... I just started getting an error while syncing with the old version, so I can't use that anymore either. PHP is completely unusable until this gets fixed.

**Comment by jgoldshlag** [comment]
Can you guy trying installing this from Microsoft https://www.microsoft.com/en-us/download/details.aspx?id=26368 and see if it fixes things?

**Comment by zedekblue** [comment]
Still getting the error. Tried both 86x & 64x, and rebooting, reinstalling, and repairing.

**Comment by runorhits** [comment]
just started getting this error today, app was working fine a few weeks ago when i used it last. already tried messing with the temp file permissions like google results give me and also reinstalling both versions of vcredist

**Comment by johns996** [comment]
I just ran the file you linked @jgoldshlag but I still get the same error when running the newest version of the proxy.

**Comment by tiniestkid** [comment]
Also having this issue. Installing the file @jgoldshlag didn't work for me either. I was able to extract python27.dll from C:\Users\USERNAME\AppData\Local\Temp\_MEI85962\. I tried opening it in Notepad and Notepad++ but it showed up as unrecognizable characters.

I uploaded the file to Google Drive here:
[https://drive.google.com/file/d/0BzYV9QGmpUqNbkU2VWVaNElZUzQ/view?usp=sharing](https://drive.google.com/file/d/0BzYV9QGmpUqNbkU2VWVaNElZUzQ/view?usp=sharing)

Hopefully this helps.

**Comment by tiniestkid** [comment]
Just tried running versions 2.5 & 2.4. 2.5 doesn't work but 2.4 does. Version 2.5 gives the same error so something added in Version 2.5 must have caused the problem. I extracted python27.dll from C:\Users\USERNAME\AppData\Local\Temp_MEI85962 again. I tried opening it in Notepad and Notepad++ but it showed up as unrecognizable characters again. I'm probably using the wrong program to open this.

I uploaded the python27.dll from Version 2.4 to Google Drive here:
[https://drive.google.com/file/d/0BzYV9QGmpUqNb1B6U2NuTkh0Qlk/view?usp=sharing](https://drive.google.com/file/d/0BzYV9QGmpUqNb1B6U2NuTkh0Qlk/view?usp=sharing)

@jgoldshlag Maybe try comparing the differences in code between the two files? You might find the source of the error there.

**Comment by jgoldshlag** [comment]
Can anyone who was having this try my latest release? I changed a couple options in the packager, and I hope it might fix this

**Comment by johns996** [comment]
I just tested it on my machine and the DLL error is gone.  Thanks for fixing this!

**Comment by jgoldshlag** [comment]
Great, thanks for trying it!
