### ISSUE TITLE
Havent been able to sync with newest version.

### ISSUE THREAD

**Issue by Sprumples** [jgoldshlag/padherder_proxy#31]
Error doing sync:
Traceback (most recent call last):
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 230, in do_sync
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 24, in xp_at_level
TypeError: object of type 'NoneType' has no len()

Please report this error on github

**Comment by PaPa-G17Hub** [comment]
I have the same issue using the pre-compiled release

**Comment by jgoldshlag** [comment]
Are you guys using the latest release? Are you using the Japanese version of PAD? This error usually means GH added a new XP curve, I will check to see if I need to add it. Also, make sure you are using the latest release.

**Comment by PaPa-G17Hub** [comment]
I used the latest release

**Comment by zedekblue** [comment]
Finally got the proxy to actually open by running from source... Now I'm just getting this same error.

```
Downloaded current padherder box
Error doing sync:
Traceback (most recent call last):
  File "C:\padherder_proxy\padherder_sync.py", line 230, in do_sync
    mon_array[1] = min(mon_array[1], xp_at_level(base_data['xp_curve'], base_data['max_level']))
  File "C:\padherder_proxy\padherder_sync.py", line 24, in xp_at_level
    if level > len(curve) - 1:
TypeError: object of type 'NoneType' has no len()
```

EDIT: Spent a few hours learning the code and finding the issue... Then realizing I only have a handful of new cards that could have caused this. 

[3011](http://www.puzzledragonx.com/en/monster.asp?n=3011), [3012](http://www.puzzledragonx.com/en/monster.asp?n=3012)
& (JP) [All Pepper Variants](http://www.puzzledragonx.com/en/monster.asp?n=3195)

The 8,888,888 xp curve seems to be in the code, however still unsupported by Padherder, which I'm guessing is the real issue.

**Comment by zedekblue** [comment]
Temporary workaround for anyone dealing with this issue:
You'll have to run from source, but removing the XP cap, line 230, of padherder_sync.py, should work. Not sure what side effects this has, and if all xp will be off/incorrect, but at least you can sync.

**Comment by jgoldshlag** [comment]
I think I just pushed the fix for this, going to cut a new release and hopefully it should work
