### ISSUE TITLE
Stalls during connection

### ISSUE THREAD

**Issue by thunderchunky94** [jgoldshlag/padherder_proxy#32]
I don't know if this is the right place to leave this, but it's worth a shot.  I've done the setup and everything seems to be working fine, until it comes time to connect to the proxy. The "DNS Proxy Log" tab is active and always displays at least something. Sometimes it's about 6 lines, sometimes it's closer to 30, but it never finishes and just hangs indefinitely.  If anyone has seen this or fixed it or even recognized what the symptoms are, I'd appreciate any help! Thanks!

**Comment by zedekblue** [comment]
Post the logs?
I know of a couple issues I've had with stalling, but it's impossible to tell if they're the same without any proof.

**Comment by thunderchunky94** [comment]
This is a pretty good sample.  It made it further than sometimes, less than others. Thanks again!

Request: [10.0.0.5:43004] (udp) / 'connectivitycheck.android.com.' (A)
Reply: [10.0.0.5:43004] (udp) / 'connectivitycheck.android.com.' (A) / RRs: A
Request: [10.0.0.5:56012] (udp) / 'connectivitycheck.android.com.' (A)
Reply: [10.0.0.5:56012] (udp) / 'connectivitycheck.android.com.' (A) / RRs: A
Request: [10.0.0.5:38832] (udp) / 'epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.' (AAAA)
Reply: [10.0.0.5:38832] (udp) / 'epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.' (AAAA) / RRs: CNAME
Request: [10.0.0.5:38117] (udp) / 'ipv4only.arpa.' (AAAA)
Reply: [10.0.0.5:38117] (udp) / 'ipv4only.arpa.' (AAAA) / RRs: 
Request: [10.0.0.5:64912] (udp) / 'epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.' (A)
Reply: [10.0.0.5:64912] (udp) / 'epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.' (A) / RRs: CNAME,A
Request: [10.0.0.5:56754] (udp) / 'ipv4only.arpa.' (A)
Reply: [10.0.0.5:56754] (udp) / 'ipv4only.arpa.' (A) / RRs: A,A
Request: [10.0.0.5:60661] (udp) / 'connectivitycheck.android.com.' (A)
Reply: [10.0.0.5:60661] (udp) / 'connectivitycheck.android.com.' (A) / RRs: A
Request: [10.0.0.5:43642] (udp) / 'connectivitycheck.android.com.' (A)
Reply: [10.0.0.5:43642] (udp) / 'connectivitycheck.android.com.' (A) / RRs: A
Request: [10.0.0.5:58806] (udp) / 'mobile.pipe.aria.microsoft.com.' (AAAA)
Reply: [10.0.0.5:58806] (udp) / 'mobile.pipe.aria.microsoft.com.' (AAAA) / RRs: CNAME,CNAME,CNAME,CNAME
Request: [10.0.0.5:58002] (udp) / 'www.googleapis.com.' (AAAA)
Reply: [10.0.0.5:58002] (udp) / 'www.googleapis.com.' (AAAA) / RRs: CNAME,AAAA

**Comment by thunderchunky94** [comment]
Nevermind.  I just had to turn off my firewall long enough for it to sync up.  Now it works perfectly!

Thanks guys!
