### ISSUE TITLE
No .exe to run

### ISSUE THREAD

**Issue by TackyBrad** [jgoldshlag/padherder_proxy#35]
There is no `pyinstaller.exe` in my python scripts folder that the batch file is trying to point to. When I run the padherder_proxy.py manually, it tells me the `No Module named libmproxy found.`

Thus, this is entirely unusable for me in this state. I downloaded the latest zip and am running python version 2.7.12. Pip is a tad behind, but my node and npm are both up to date (don't think this project uses those anyway?)

Please help, as I would love to be able to get this going. Is the pyinstaller.exe something that was supposed to come with python? Tried doing a git clone to download your files and the same result. Please let me know.

Windows 7 OS

**Comment by etogithub** [comment]
I had a similar error after doing a system upgrade.  I had to manually install mitmproxy version 0.16.  It appears that more recent versions of mitmproxy dropped libmproxy.

Give that a shot:   pip install mitmproxy=0.16

**Comment by jgoldshlag** [comment]
You shouldn't need to run the batch file, you should be downloading a release from https://github.com/jgoldshlag/padherder_proxy/releases

If you want to run from source, you still don't need to run that batch file, that is just to create a release.
