### ISSUE TITLE
Can't connect/sync: error 10013

### ISSUE THREAD

**Issue by MatthewRobo** [jgoldshlag/padherder_proxy#39]
Using padherder_proxy v2.8
Using iOS 10.2.1
Using Windows 10 Anniversary Edition
Firewall enabled
MITMproxy recently reinstalled on iOS
HTTP proxy set to "auto"
No VPN enabled
Issues began occurring approximately two weeks ago
Before, padherder_proxy worked perfectly
Not sure what I'm doing wrong

Proxy status is as follows:
```
proxy started
Got DNS Request
Error starting HTTPS proxy: Error starting proxy server: error(10013, 'An attempt was made to access a socket in a way forbidden by its access permissions')
````
Error occurs right after tapping to start in PAD title screen

DNS Proxy Log is as follows:
```
Request: [172.21.103.98:54326] (udp) / 'www.icloud.com.' (A)
Reply: [172.21.103.98:54326] (udp) / 'www.icloud.com.' (A) / RRs: CNAME,CNAME,CNAME,A
Request: [172.21.103.98:49503] (udp) / 'apple.com.' (A)
Reply: [172.21.103.98:49503] (udp) / 'apple.com.' (A) / RRs: A,A,A
Request: [172.21.103.98:57245] (udp) / 'www.apple.com.' (A)
Reply: [172.21.103.98:57245] (udp) / 'www.apple.com.' (A) / RRs: CNAME,CNAME,CNAME,A
Request: [172.21.103.98:62686] (udp) / 'wpad.williston.com.' (A)
Reply: [172.21.103.98:62686] (udp) / 'wpad.williston.com.' (A) / RRs: 
Request: [172.21.103.98:62400] (udp) / 'p6-buy.itunes.apple.com.' (A)
Reply: [172.21.103.98:62400] (udp) / 'p6-buy.itunes.apple.com.' (A) / RRs: CNAME,A
Request: [172.21.103.98:65105] (udp) / 'api.growmobile.com.' (A)
Reply: [172.21.103.98:65105] (udp) / 'api.growmobile.com.' (A) / RRs: CNAME,A,A,A,A
Request: [172.21.103.98:49172] (udp) / 'dl-na.padsv.gungho.jp.' (A)
Reply: [172.21.103.98:49172] (udp) / 'dl-na.padsv.gungho.jp.' (A) / RRs: A,A,A,A,A,A,A,A
Request: [172.21.103.98:55994] (udp) / 'ssl.google-analytics.com.' (A)
Reply: [172.21.103.98:55994] (udp) / 'ssl.google-analytics.com.' (A) / RRs: CNAME,A
Request: [172.21.103.98:50055] (udp) / 'api-na-iosv2.padsv.gungho.jp.' (A)
Reply: [172.21.103.98:50055] (udp) / 'api-na-iosv2.padsv.gungho.jp.' (A) / RRs: A
```

Puzzle & Dragons 9.6.3 error is as follows:
```
A connection error has occurred.
Error Code: 101
```
Error occurs right after tapping to start in PAD title screen.

**Comment by jgoldshlag** [comment]
I actually hit this very error just this morning. Apparently the newest version of Skype thought it would be super fun to listen on port 80 and 443. Why? Who knows! Assuming you might have Skype running, try completely closing it and see if the error goes away. If it does, there is an option to turn off the listening If you go to Tools->Options->Advanced->Connection and uncheck the "Use port 80 and 443 for additional incoming connections" checkbox.

If that doesn't solve it, run the command prompt as an administrator and run "netstat -ab" and check the line that looks like <your IP address>:443. It should tell you which process is using the port in question.

**Comment by MatthewRobo** [comment]
That's... a hell of a coincidence.

I closed Skype and ran padherder_proxy. It solved the issue.

I haven't tried to see if unchecking the box works, but I did it anyways.

Thank you for the solution.

---

Is there a way I can mark this as "closed" or "solved"?

**Comment by jgoldshlag** [comment]
I can... :)
