### ISSUE TITLE
Proxy seems to no longer function with PAD 11.0.2

### ISSUE THREAD

**Issue by swisener** [jgoldshlag/padherder_proxy#41]
App gives a connection error when trying to go through the proxy. The proxy sees the DNS request, but is unable to complete the handshake. From the DNS proxy log:

```
Request: [192.168.7.23:53858] (udp) / 'api-na-iosv2.padsv.gungho.jp.' (A)
Reply: [192.168.7.23:53858] (udp) / 'api-na-iosv2.padsv.gungho.jp.' (A) / RRs: A
Request: [192.168.7.23:53858] (udp) / 'api-na-iosv2.padsv.gungho.jp.' (A)
Reply: [192.168.7.23:53858] (udp) / 'api-na-iosv2.padsv.gungho.jp.' (A) / RRs: A
```

PAD displays an error: "A connection error has occurred. Error Code: 101"

**Comment by zetix** [comment]
Go to Settings > General > Certificate Trust Settings > Toggle mitmproxy ON

**Comment by swisener** [comment]
The issue was indeed with the certificate, but it wasn't the trust settings. I had to delete the certificate and recreate it. It was probably an iOS upgrade that broke things.
