### ISSUE TITLE
Malware warning when downloading projects

### ISSUE THREAD

**Issue by Tarkus697** [jgoldshlag/padherder_proxy#46]
I'm getting a warning that the latest project is infected by Malware when I download it.  Anyone else getting this?  I'm using Avast for my AV.

**Comment by jgoldshlag** [comment]
I've heard that some AV is classifying it as malware. It certainly does stuff that is similar to what some kinds of malware does, like proxying web traffic. If you aren't comfortable running it, don't. The source is available, and you can look at exactly what it does. There isn't much I can do about it from my end.

**Comment by edale2** [comment]
I got a detection as malware from AVG.

There actually IS something you can do, submit it to AVG as a false positive, and let them review it. Usually programs get cleared and definitions updated within a few days.

**Comment by jgoldshlag** [comment]
Submitted to AVG, I am not going to play whack-a-mole with all the other AV products but if someone else wants to, feel free!
