### ISSUE TITLE
Any chance to integrate this into Fiddler?

### ISSUE THREAD

**Issue by Endracion** [jgoldshlag/padherder_proxy#5]
Fiddler: http://www.telerik.com/fiddler

There's an inspector type plugin that was made for Final Fantasy Record Keeper: https://github.com/karryt/ffrk-inspector
It has some nifty features which you can see in this screenshot album: https://imgur.com/a/5dNAf

It parses the json data it intercepts and can display what's coming up in the next dungeon, etc.
If I remember correctly, doing the same kind of thing in PAD would allow us to see what's going to appear on the next floors and also what will be dropping, since all this is decided at the time you enter the dungeon and not done on the go.
That's without mentioning the large amount of data you could actually gather automatically, if you're playing with the tool open (which is what we do in FFRK; it collects drop data which is shared among all clients).
Of course this is beyond the scope of mere PadHerder sync, but that can be a simple button in the interface, and you could sort your monsters inside the plugin itself (we have that for equipment in FFRK once again), so there's so much more that it could be extended to!

Hope you'd find this interesting at the very least :D

**Comment by jgoldshlag** [comment]
I think the answer is that it probably could be done, but I would be worried about GH not being a big fan of me doing it, and potentially banning me. It doesn't seem worth the risk to me.

**Comment by Endracion** [comment]
For argument's sake, if there are any rules about reading the data, they're already been infringed upon with the proxy. It's doing nothing different, just intercepting data the same way. So if you're worried about a ban, then the current version vs a more expanded set of tools would be the same vs their ToS.

But in any case, if you're not more interested than that, there's nothing more to say, thanks for considering it!

**Comment by jgoldshlag** [comment]
I'm interested, but I am more worried about getting banned...
