### ISSUE TITLE
Requires 'root' on *nix systems (patch supplied)

### ISSUE THREAD

**Issue by TheKat** [jgoldshlag/padherder_proxy#9]
Because PADHerder Proxy needs to bind to ports TCP 443 and UDP 53 it requires root on *nix based systems.

I'm attaching a patch that allows for PADHerder Proxy users to bind them to other ports so python/padherder_proxy.py does not need to be run as root. This is a security enhancement, as well as stops PADHerder Proxy from creating root-owned files.

The included help includes examples for simple commands to deal with the ports moving.

Also included a few fixes for error cases I ran into dealing with some unhandled exceptions from libmproxy and dnslib.

Tested on Windows 10 and Linux.

Include if you like :)

[0001-Config-options-to-allow-runnin-as-non-root-user-on-n.patch.txt](https://github.com/jgoldshlag/padherder_proxy/files/129838/0001-Config-options-to-allow-runnin-as-non-root-user-on-n.patch.txt)

**Comment by jgoldshlag** [comment]
Patch applied in the latest release
